version: "2"

services:
  postgres:
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    restart: always

  elasticsearch:
    image: elasticsearch
      
  node:
    build:
      context: .
      dockerfile: ./node.Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - elasticsearch
    command: ["npm", "start"]
